console.log('daily check');
console.log('day_2');
console.log('day_3');
console.log('day_4');
console.log('day_5');
console.log('day_6');
console.log('day_7');
console.log('day_8');
console.log('day_9');
console.log('day_10');
console.log('day_11');
console.log('day_12');
console.log('day_13');
console.log('day_14');
